---
# ip_address:
# domain_name:

# pterodactyl_app:
#   env:
#   debug:
#   key:
#   theme:
#   timezone:
#   url:
#   locale:
#   environment_only:

# pterodactyl_database:
#   engine:
#   host:
#   port:
#   name:
#   user:
#   password:

# remote_admin_database:
#   username:
#   password:

# pterodactyl_redis:
#   host:
#   port:
#   password:
